// Core/Services/AIQuizGenerationService.swift
// SlangCheck
//
// Protocol + value types for AI-powered quiz question enhancement.
// Enriches quiz questions with fresh sentences and definition distractors
// so each session feels unique. Zero UIKit/FoundationModels imports.

import Foundation

// MARK: - AIQuizEnhancement

/// AI-generated enrichment for a single quiz question.
///
/// `exampleSentence` replaces the static sentence stored in `SlangTerm.exampleSentence`
/// so every quiz session presents a different usage context, preventing rote
/// memorisation of a fixed sentence.
///
/// `definitionDistractors` are three plausible-but-wrong definitions used for
/// `.definitionPick` questions. They are generated by the AI and tuned to sound
/// convincing without being accurate, improving quiz difficulty and engagement.
/// For `.termPick` and `.fillInBlank`, the static term-pool distractors are used
/// instead (real glossary terms make better wrong-term answers than AI inventions).
public struct AIQuizEnhancement: Sendable {

    /// A fresh, contextually authentic example sentence using the slang term.
    public let exampleSentence: String

    /// Exactly three plausible but incorrect definitions for the term.
    /// Used as distractors in `.definitionPick` questions.
    public let definitionDistractors: [String]

    public init(exampleSentence: String, definitionDistractors: [String]) {
        precondition(definitionDistractors.count == 3,
                     "AIQuizEnhancement requires exactly 3 definitionDistractors.")
        self.exampleSentence        = exampleSentence
        self.definitionDistractors  = definitionDistractors
    }
}

// MARK: - AIQuizGenerationService

/// Enriches a quiz question with AI-generated content.
///
/// Called per-term during `GenerateQuizUseCase.execute()`. Returns `nil` when
/// Apple Intelligence is unavailable; the use case falls back to static content.
///
/// The `questionType` parameter allows the AI to tailor its output — e.g.,
/// generating a sentence fragment for `.fillInBlank` vs. a conversational sentence
/// for `.definitionPick`.
public protocol AIQuizGenerationService: Sendable {

    /// Generates enriched content for a quiz question about `term`.
    ///
    /// - Parameters:
    ///   - term: The `SlangTerm` being tested.
    ///   - allTerms: The full glossary, used as negative examples to ensure
    ///     distractors don't accidentally describe another real term.
    ///   - questionType: Controls the style of the generated example sentence.
    /// - Returns: An `AIQuizEnhancement`, or `nil` if the model is unavailable.
    func enhance(
        term: SlangTerm,
        allTerms: [SlangTerm],
        questionType: QuestionType
    ) async -> AIQuizEnhancement?
}
